version: "3.7"
services:
  db:
    image: mariadb:10.9.2
    volumes:
      - ./db-data/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vip
      MYSQL_USER: jefao
      MYSQL_PASSWORD: jefao
    ports:
      - "3306:3306"